### ISSUE TITLE
[FE]Add fullscreen function to button widget

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#159]
# This is the front-end development task of #158 
## TODOs
- [ ] Edit property on manifest file 
- [ ] Add `full screen` type to button widget props type
- [ ] expose the Re:Earth Plugin API which allows the plugin to show app with full screen
- [ ] Modify the button widget

**Comment by airslice** [comment]
Might not be necessary since all browser has builtin fullscreen function.

**Comment by airslice** [comment]
Might not be necessary since all browser has builtin fullscreen function.
